# Generated by Django 2.0.3 on 2019-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='include',
            field=models.CharField(max_length=2024, null=True, verbose_name='前置config/test'),
        ),
    ]
