# Generated by Django 2.0.3 on 2020-03-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_auto_20191107_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='name',
            field=models.CharField(max_length=250, verbose_name='用例/配置名称'),
        ),
    ]
